#!/usr/bin/env python3
"""Generate `results/INDEX.md`: every experiment, its script, and its report.

The project's results live in ~40 generated markdown files whose provenance is
only recoverable by grepping. This walks `results/*.md`, recovers each one's
title and the script that writes it, and emits one table. Regenerate it after
adding an experiment rather than editing it by hand -- a hand-maintained index
goes stale the first time it is inconvenient.

    python scripts/46_index.py
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
SCRIPTS = ROOT / "scripts"


def writer_of(report: Path) -> str:
    """The script that writes this report, found by grep over candidate keys.

    Scripts build their output path with an f-string -- ``f"c9_domain_causal_
    {config}_{label}.md"`` -- so the literal filename appears nowhere. Matching
    only the full name reported 29 of 50 reports as orphans, every one of them
    wrongly. Try the full name, then the stem, then the stem with the model
    suffix stripped, and stop at the first key that hits.
    """
    keys = [report.name, report.stem]
    stem = report.stem
    for marker in ("_qwen3", "_gemma"):
        if marker in stem:
            keys.append(stem.split(marker)[0])
            break
    texts = {}
    for script in sorted(SCRIPTS.glob("*.py")):
        try:
            texts[script.name] = script.read_text()
        except UnicodeDecodeError:
            continue
    for key in keys:
        if len(key) < 4:
            continue
        hits = [name for name, text in texts.items() if key in text]
        if hits:
            return ", ".join(f"`scripts/{h}`" for h in hits)
    return "_unknown_"


def sweep_of(script_names: str) -> str:
    """The modal_app command a report's script depends on, if it names one."""
    names = re.findall(r"scripts/(\S+?)`", script_names)
    found: set[str] = set()
    for name in names:
        path = SCRIPTS / name
        if not path.exists():
            continue
        text = path.read_text()
        for m in re.finditer(r"modal_app\.py\s+([a-z_0-9]+)", text):
            found.add(m.group(1))
    return ", ".join(f"`{c}`" for c in sorted(found)) if found else "-"


def main() -> None:
    rows = []
    for report in sorted(RESULTS.glob("*.md")):
        if report.name == "INDEX.md":
            continue
        first = ""
        for line in report.read_text().splitlines():
            if line.startswith("#"):
                first = line.lstrip("#").strip()
                break
        lines = len(report.read_text().splitlines())
        writer = writer_of(report)
        rows.append((report.name, first, lines, writer, sweep_of(writer)))

    try:
        head = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
            capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        head = "unknown"

    out = [
        "# Results index",
        "",
        f"Generated by `scripts/46_index.py` at commit `{head}`. "
        f"{len(rows)} reports. Every row is a file written by a script from "
        "data on the Modal results volume; none of it is hand-typed, and the "
        "methodology for each is in its own preamble and in the generating "
        "script's docstring.",
        "",
        "**`results/` is gitignored.** Nothing in this table is version "
        "controlled, so a lost volume or a cleared working tree loses all of "
        "it. That is a standing risk, not a decision anyone made.",
        "",
        "| report | title | lines | written by | sweep |",
        "|---|---|---|---|---|",
    ]
    for name, title, n, writer, sweep in rows:
        out.append(f"| `{name}` | {title} | {n} | {writer} | {sweep} |")

    orphans = [r for r in rows if r[3] == "_unknown_"]
    if orphans:
        out += [
            "",
            "## Reports with no generating script found",
            "",
            "These are hand-written or their script was renamed. A hand-written "
            "result cannot be regenerated and should be treated with more "
            "suspicion than a generated one.",
            "",
        ] + [f"- `{r[0]}` -- {r[1]}" for r in orphans]

    (RESULTS / "INDEX.md").write_text("\n".join(out) + "\n")
    print(f"wrote {RESULTS / 'INDEX.md'} ({len(rows)} reports, {len(orphans)} orphans)")


if __name__ == "__main__":
    main()
